<?php
return [
    'warrior_fury' => [
        'label' => 'Warrior - Fury',
        'class' => 'Warrior',
        'spec' => 'Fury',
        'weights' => [
            'strength' => 1.00,
            'agility' => 0.45,
            'stamina' => 0.20,
            'attack_power' => 0.65,
            'hit' => 0.95,
            'crit' => 0.80,
            'haste' => 0.45,
            'expertise' => 0.90,
            'armor_pen' => 0.55,
        ],
    ],
    'warrior_protection' => [
        'label' => 'Warrior - Protection',
        'class' => 'Warrior',
        'spec' => 'Protection',
        'weights' => [
            'stamina' => 1.00,
            'strength' => 0.35,
            'defense' => 0.95,
            'dodge' => 0.80,
            'parry' => 0.75,
            'block' => 0.55,
            'block_value' => 0.45,
            'hit' => 0.35,
            'armor' => 0.03,
        ],
    ],
    'rogue_combat' => [
        'label' => 'Rogue - Combat',
        'class' => 'Rogue',
        'spec' => 'Combat',
        'weights' => [
            'agility' => 1.00,
            'strength' => 0.55,
            'stamina' => 0.15,
            'attack_power' => 0.60,
            'hit' => 0.95,
            'crit' => 0.78,
            'haste' => 0.40,
            'expertise' => 0.85,
        ],
    ],
    'hunter_marksman' => [
        'label' => 'Hunter - Marksman',
        'class' => 'Hunter',
        'spec' => 'Marksman',
        'weights' => [
            'agility' => 1.00,
            'stamina' => 0.18,
            'attack_power' => 0.58,
            'ranged_attack_power' => 0.72,
            'hit' => 0.92,
            'crit' => 0.80,
            'haste' => 0.42,
            'armor_pen' => 0.48,
        ],
    ],
    'mage_frost' => [
        'label' => 'Mage - Frost',
        'class' => 'Mage',
        'spec' => 'Frost',
        'weights' => [
            'intellect' => 0.70,
            'spirit' => 0.20,
            'stamina' => 0.12,
            'spell_power' => 1.00,
            'spell_hit' => 0.90,
            'spell_crit' => 0.72,
            'spell_haste' => 0.42,
            'mana_regen' => 0.35,
        ],
    ],
    'warlock_destruction' => [
        'label' => 'Warlock - Destruction',
        'class' => 'Warlock',
        'spec' => 'Destruction',
        'weights' => [
            'intellect' => 0.68,
            'spirit' => 0.18,
            'stamina' => 0.18,
            'spell_power' => 1.00,
            'spell_hit' => 0.92,
            'spell_crit' => 0.75,
            'spell_haste' => 0.45,
            'mana_regen' => 0.28,
        ],
    ],
    'priest_holy' => [
        'label' => 'Priest - Holy',
        'class' => 'Priest',
        'spec' => 'Holy',
        'weights' => [
            'intellect' => 0.85,
            'spirit' => 0.90,
            'stamina' => 0.10,
            'spell_power' => 0.88,
            'mana_regen' => 1.00,
            'spell_crit' => 0.30,
            'spell_haste' => 0.35,
        ],
    ],
    'priest_shadow' => [
        'label' => 'Priest - Shadow',
        'class' => 'Priest',
        'spec' => 'Shadow',
        'weights' => [
            'intellect' => 0.72,
            'spirit' => 0.32,
            'stamina' => 0.14,
            'spell_power' => 1.00,
            'spell_hit' => 0.94,
            'spell_crit' => 0.65,
            'spell_haste' => 0.40,
            'mana_regen' => 0.30,
        ],
    ],
    'paladin_holy' => [
        'label' => 'Paladin - Holy',
        'class' => 'Paladin',
        'spec' => 'Holy',
        'weights' => [
            'intellect' => 1.00,
            'spirit' => 0.18,
            'stamina' => 0.12,
            'spell_power' => 0.82,
            'mana_regen' => 0.95,
            'spell_crit' => 0.42,
            'spell_haste' => 0.28,
        ],
    ],
    'paladin_retribution' => [
        'label' => 'Paladin - Retribution',
        'class' => 'Paladin',
        'spec' => 'Retribution',
        'weights' => [
            'strength' => 1.00,
            'agility' => 0.35,
            'stamina' => 0.22,
            'attack_power' => 0.62,
            'hit' => 0.88,
            'crit' => 0.74,
            'haste' => 0.38,
            'spell_power' => 0.12,
        ],
    ],
    'druid_feral' => [
        'label' => 'Druid - Feral',
        'class' => 'Druid',
        'spec' => 'Feral',
        'weights' => [
            'strength' => 0.72,
            'agility' => 1.00,
            'stamina' => 0.24,
            'attack_power' => 0.58,
            'hit' => 0.88,
            'crit' => 0.72,
            'haste' => 0.30,
            'armor' => 0.01,
        ],
    ],
    'druid_restoration' => [
        'label' => 'Druid - Restoration',
        'class' => 'Druid',
        'spec' => 'Restoration',
        'weights' => [
            'intellect' => 0.88,
            'spirit' => 1.00,
            'stamina' => 0.10,
            'spell_power' => 0.82,
            'mana_regen' => 0.95,
            'spell_crit' => 0.18,
            'spell_haste' => 0.28,
        ],
    ],
    'shaman_enhancement' => [
        'label' => 'Shaman - Enhancement',
        'class' => 'Shaman',
        'spec' => 'Enhancement',
        'weights' => [
            'strength' => 0.80,
            'agility' => 0.90,
            'stamina' => 0.18,
            'attack_power' => 0.62,
            'hit' => 0.90,
            'crit' => 0.72,
            'haste' => 0.38,
            'spell_power' => 0.16,
        ],
    ],
    'shaman_restoration' => [
        'label' => 'Shaman - Restoration',
        'class' => 'Shaman',
        'spec' => 'Restoration',
        'weights' => [
            'intellect' => 0.92,
            'spirit' => 0.40,
            'stamina' => 0.12,
            'spell_power' => 0.84,
            'mana_regen' => 1.00,
            'spell_crit' => 0.34,
            'spell_haste' => 0.26,
        ],
    ],
];
