<?php

if (!function_exists('spp_server_realmlist_lookup_host')) {
    function spp_server_realmlist_lookup_host(int $realmId): string
    {
        $host = '';

        if (function_exists('spp_get_pdo')) {
            try {
                $pdo = spp_get_pdo('realmd', $realmId);
                $stmt = $pdo->prepare('SELECT `address` FROM `realmlist` WHERE `id` = ? LIMIT 1');
                $stmt->execute(array($realmId));
                $row = $stmt->fetch(PDO::FETCH_ASSOC);
                if (!empty($row['address'])) {
                    $host = trim((string)$row['address']);
                }
            } catch (Throwable $e) {
                $host = '';
            }
        }

        return $host;
    }
}

if (!function_exists('spp_server_realmlist_endpoint_state')) {
    function spp_server_realmlist_endpoint_state(array $args = array()): array
    {
        $query = is_array($args['query'] ?? null) ? $args['query'] : $_GET;
        $server = is_array($args['server'] ?? null) ? $args['server'] : $_SERVER;
        $realmId = isset($query['realm']) ? (int)$query['realm'] : 1;
        $host = '';
        $clientConnectionHost = '';

        if (!empty($args['client_connection_host'])) {
            $clientConnectionHost = trim((string)$args['client_connection_host']);
        } elseif (!empty($GLOBALS['clientConnectionHost'])) {
            $clientConnectionHost = trim((string)$GLOBALS['clientConnectionHost']);
        } else {
            $configProtected = dirname(__DIR__, 2) . '/config/config-protected.php';
            if (!empty($_SERVER['DOCUMENT_ROOT']) && is_file($configProtected)) {
                require_once $configProtected;
            }

            if (isset($clientConnectionHost) && is_string($clientConnectionHost)) {
                $clientConnectionHost = trim($clientConnectionHost);
            }
        }

        $host = spp_server_realmlist_lookup_host($realmId);

        if ($host === '' && $clientConnectionHost !== '') {
            $host = $clientConnectionHost;
        }

        if ($host === '' && !empty($server['HTTP_HOST'])) {
            $host = preg_replace('/:\d+$/', '', (string)$server['HTTP_HOST']);
        }

        if ($host === '') {
            $host = (string)($server['SERVER_ADDR'] ?? '127.0.0.1');
        }

        $safeRealmId = max(1, $realmId);
        $filename = ($safeRealmId === 1) ? 'realmlist.wtf' : ('realmlist-' . $safeRealmId . '.wtf');

        return array(
            'realmId' => $realmId,
            'filename' => $filename,
            'contentType' => 'text/plain; charset=UTF-8',
            'contentDisposition' => 'attachment; filename="' . $filename . '"',
            'body' => '# autogenerated by website' . "\r\n" . 'set realmlist ' . $host . "\r\n",
        );
    }
}

if (!function_exists('spp_server_emit_realmlist_endpoint')) {
    function spp_server_emit_realmlist_endpoint(array $args = array()): void
    {
        $state = spp_server_realmlist_endpoint_state($args);

        header('Content-Type: ' . $state['contentType']);
        header('Content-Disposition: ' . $state['contentDisposition']);

        echo $state['body'];
        exit;
    }
}
